---
apiVersion: v1
kind: Pod
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  containers:
  - name: localstack
    image: localstack/localstack
    env:
      - name: SERVICES
        value: s3,ec2,sqs,dynamodb # https://docs.aws.amazon.com/cli/latest/reference/#available-services

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  type: ClusterIP
  clusterIP: 10.96.10.1
  ports:
  - name: http
    protocol: TCP
    port: 4566
    targetPort: 4566

#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: localstack
#subsets:
#- addresses:
#  - ip: 10.96.10.1
#  ports:
#  - protocol: TCP
#    port: 4566

---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  labels:
    app: foo
spec:
  #restartPolicy: Never
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["/bin/sleep"]
    args: ["3600"]
  - name: golang
    image: golang:1.15
    command: ["/bin/sleep"]
    args: ["3600"]

  hostAliases:
  - ip: "10.96.10.1"
    hostnames:
    - "foo.bar"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
spec:
  selector:
    matchLabels:
      type: gce-pv
    matchExpressions:
    - key: environment
      operator: In
      values:
      - stg
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
