apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: http
    nodePort: 30080
  selector:
    app: sample-app


---
apiVersion: v1
kind: Service
metadata:
  name: sample-lb-fw
spec:
  type: LoadBalancer
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: http
    nodePort: 30082
  selector:
    app: sample-app
  sessionAffinity: ClientIP
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  topologyKeys:
  - kubernetes.io/hostname
  - "*"

---
apiVersion: v1
kind: Service
metadata:
  name: sample-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: sample-app
