---
apiVersion: v1
kind: Service
metadata:
  name: sample-none-selector
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: sample-none-selector
subsets:
- addresses:
  - ip: 10.244.236.106
  ports:
  - protocol: TCP
    port: 4566

# $ kubectl exec -it pod/sample-named-port-pod-81 -- /bin/sh


# helm repo add localstack-repo http://helm.localstack.cloud
# helm upgrade --install localstack localstack-repo/localstack


# helm inspect values localstack-repo/localstack | tee localstack-config.yml


