apiVersion: v1
kind: Pod
metadata:
  name: sample-subdomain
  labels:
    app: sample-app
spec:
  hostname: sample-hostname
  subdomain: sample-subdomain
  containers:
  - name: nginx-container
    image: amsy810/tools:v2.0

---
apiVersion: v1
kind: Service
metadata:
  name: sample-subdomain
spec:
  type: ClusterIP
  clusterIP: None
  ports: []
  selector:
    app: sample-app

#
# kubectl run --image=amsy810/tools:v2.0 --restart=Never --rm -i testpod \
#   --command -- \
#   dig +short sample-hostname.sample-subdomain.default.svc.cluster.local
# 10.244.236.102
# 10.244.236.98
#
