apiVersion: v1
kind: Pod
metadata:
  name: sample-entrypoint
spec:
  containers:
  - name: redis-container
    image: redis:3.2
    command: ["/bin/sleep"] # ENTRYPOINT in Dockerfile
    args: ["3600"] # CMD in Dockerfile
