apiVersion: batch/v1
kind: Job
metadata:
  name: sample-hello-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 5']
      restartPolicy: OnFailure
